### ISSUE TITLE
Wrong asset file under 'Releases'

### ISSUE THREAD

**Issue by EmilHovgaard** [OfficeDev/microsoft-teams-apps-howto#1]
I was looking to download the asset .zip file but see that its the 'GetConnected' app which has been release; I assume it should have been 'HowTo'
![Capture](https://user-images.githubusercontent.com/18255975/133075370-a85897c1-7fc7-41c2-abed-2d668e19d93d.PNG)

**Comment by ShuoChen-MS** [comment]
Hey Emil, Thanks so much for reaching out, it is already fixed with the latest release.
